# Generated by Django 5.1.7 on 2025-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_place_admin",
            field=models.BooleanField(
                default=False,
                help_text="Indique si l'utilisateur est administrateur d'un lieu et peut endorser des badges.",
                verbose_name="administrateur de lieu",
            ),
        ),
    ]
